name: Bug Report 🐛
description: File a bug report
title: "[Bug]: <title>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as many screenshots as possible to perfectly provide the bug report :)
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you have seen!
      value: "A bug found!"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Brave
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Any Links or references? Please provide anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/SaptarshiSarkar12/notes/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
